spring:
  application:
    name: web-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/web-server/
error: path=/error
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8889